server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_rotinadafit
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      #create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect

